version: "3.9"
services:
  llame:
    build: .
    env_file: .env
    ports:
      - "8080:80"
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: llamedb
      POSTGRES_USER: llame
      POSTGRES_PASSWORD: llamapass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: